version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./data:/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: always

